#!/usr/bin/env bash
#
# A bash script for building custom kernel packages for Arch Linux.
# This is free and unencumbered software released into the public domain.
#
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.
#
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# For more information, please refer to <http://unlicense.org/>
#

VERSION="0.1.1"
DESC="A bash script for building custom kernel packages for Arch Linux"
KBUILDER_DIR="$HOME/.kbuilder"
HOOKS_DIR="/etc/kbuilder/hooks"
SOURCE_URL="https://raw.githubusercontent.com/archlinux/svntogit-packages/packages/linux/trunk"

# print function for printing output to the console
print()
{
	case $1 in
		err) echo "==> ERROR: $2" >&2 && exit 1 ;;
		nor) echo "==> $2" ;;
		low) echo " -> $2" ;;
		no) echo "$2" ;;
		nonew) echo -n " -> $2" ;;
	esac
}


# Helper for removing
remove()
{
    print nor "Deleting $1 $2"
	rm -rf "$1" || print err "Could not delete $1"
}

create()
{
    print nor "Creating $1..."
	print low "Checking if $1 exists..."
    [[ -d "$1" ]] && print low "$1 exists, removing" && remove $KBUILDER_DIR/cache
    mkdir -p $1 || print err "Could not create $1"
}

# Install the built kernel with pacman and delete the cache directory
command_install ()
{
    [[ ! -d "$KBUILDER_DIR/cache" ]] && print err "Kernel hasn't been built yet"

    print "==> Installing kernel packages with pacman..."
	comm="pacman -U $KBUILDER_DIR/cache/*.pkg.tar.zst "
    sudo $comm || print err "$comm did not complete successfully"
 
    remove $KBUILDER_DIR/cache

    print nor "Kernel installed successfully"
}



# Fetch PKGBUILD and config, modify the PKGBUILD and build the kernel like any other aur package
command_build ()
{
	create $KBUILDER_DIR/cache
 
	for fetch in PKGBUILD config; do
    	print nonew "==> Fetching $fetch... "
    	curl --silent -o $KBUILDER_DIR/cache/$fetch $SOURCE_URL/$fetch || print nonew "fail" && print no "done"
	done

	if [[ -z "$KBUILDER_PKG_NAME" ]]; then
    	print low "KBUILDER_PKG_NAME is invalid, using default: linux-kbuilder-custom"
    	KBUILDER_PKG_NAME="kbuilder-linux-custom"
    else
    	print low "variable is set to $KBUILDER_PKG_NAME"
    fi

    print nor "Setting package name to $KBUILDER_PKG_NAME..."
    sed -i "s@pkgbase=linux@pkgbase=$KBUILDER_PKG_NAME@" $KBUILDER_DIR/cache/PKGBUILD || print err "Could not set package name"

    print nor "Injecting bash shell and run-parts hook into PKGBUILD...."
    sed -i "/  make olddefconfig/a \  run-parts --regex 'kbuilder-hook-*' $HOOKS_DIR" $KBUILDER_DIR/cache/PKGBUILD
    sed -i "/  run-parts/a \  echo ''; echo 'This is an injected shell, you can apply any patches or modify the config now. Exit the shell to continue the build.'; bash" $KBUILDER_DIR/cache/PKGBUILD

    if [[ -z "$KBUILDER_BUILD_JOBS" ]]; then
        print low "KBUILDER_BUILD_JOBS is invalid, using make's default"
    else
        print low "KBUILDER_BUILD_JOBS is set to $KBUILDER_BUILD_JOBS, injecting argument into PKGBUILD"
        sed -i "s@make all@make -j$KBUILDER_BUILD_JOBS all@" $KBUILDER_DIR/cache/PKGBUILD || print err "Could not inject argument into PKGBUILD"
    fi
  
    print nor "Commenting out 'make htmldocs' in PKGBUILD..."
    sed -i "s@make htmldocs@#make htmldocs@" $KBUILDER_DIR/cache/PKGBUILD || print err "Could not uncomment 'make htmldocs' in PKGBUILD"
  
    print nor "Entering $KBUILDER_DIR/cache..."
    cd $KBUILDER_DIR/cache

    print nor "Running makepkg..."
    makepkg -s --skippgpcheck || print err "Command 'makepkg -s --skippgpcheck' did not complete successfully"

}

# Help message
help()
{
    cat <<-EOF
usage: kbuilder [help] [build] [install]

options:
    help        show this message
    build       fetch and build a kernel with makepkg
    install     install the built kernel with pacman
    version     show kbuilder version
EOF
}

# Action helper
action()
{
	[[ $EUID = "0" ]] && print err "kbuilder should not be run as root."
	for dep in curl makepkg sudo sed rm cd cat mkdir run-parts; do
		command -v $dep >/dev/null || print err "$dep is not installed"
	done
	command_$1
}

# Main command parser
case "$1" in
	install) action install ;;
	build) action build ;;
	version) print no "kbuilder $VERSION" ;;
	*) help ;;
esac
